// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8RFkz1mNjZCwzjx5BT1vb6RF0r7hOxN0',
    appId: '1:274627613482:web:50eb295bf206ff34ae0453',
    messagingSenderId: '274627613482',
    projectId: 'kitapp-a4cca',
    authDomain: 'kitapp-a4cca.firebaseapp.com',
    storageBucket: 'kitapp-a4cca.firebasestorage.app',
    measurementId: 'G-HME983H1RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsCly6lGHRu0oOHs9lF5f0Zi57OB8tOMQ',
    appId: '1:274627613482:android:0bd455a4713ccd63ae0453',
    messagingSenderId: '274627613482',
    projectId: 'kitapp-a4cca',
    storageBucket: 'kitapp-a4cca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWF43A_DpRpxmyAP1FmoXcph4pcLxGHWg',
    appId: '1:274627613482:ios:83d4e522da57ce10ae0453',
    messagingSenderId: '274627613482',
    projectId: 'kitapp-a4cca',
    storageBucket: 'kitapp-a4cca.firebasestorage.app',
    iosBundleId: 'com.example.kitapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWF43A_DpRpxmyAP1FmoXcph4pcLxGHWg',
    appId: '1:274627613482:ios:83d4e522da57ce10ae0453',
    messagingSenderId: '274627613482',
    projectId: 'kitapp-a4cca',
    storageBucket: 'kitapp-a4cca.firebasestorage.app',
    iosBundleId: 'com.example.kitapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8RFkz1mNjZCwzjx5BT1vb6RF0r7hOxN0',
    appId: '1:274627613482:web:a17d9306cc96e8c3ae0453',
    messagingSenderId: '274627613482',
    projectId: 'kitapp-a4cca',
    authDomain: 'kitapp-a4cca.firebaseapp.com',
    storageBucket: 'kitapp-a4cca.firebasestorage.app',
    measurementId: 'G-8B6JRZMDTE',
  );

}